### ISSUE TITLE
Can not use HTML entities in value attribute

### ISSUE THREAD

**Issue by zmughal** [jjn1056/Valiant#11]
For example:

```perl

input { value   => '&ShortUpArrow;&nbsp;Top' class => 'btn' },

input { value   => $self->raw('&ShortUpArrow;&nbsp;Top'), class => 'btn' }

```

Expected: HTML entities would pass through and get rendered.

Got: The ampersand is escaped.

**Comment by jjn1056** [comment]
@zmughal sorry I just saw this.  I've pushed out some changes since, has this been fixed?

**Comment by jjn1056** [comment]
@zmughal should be fixed
