### ISSUE TITLE
Add a way to skip validation before insert/update.

### ISSUE THREAD

**Issue by mat813** [jjn1056/Valiant#3]
When you have a legacy database, not all entries are actually valid, but you may want to clone entries, using `$row->copy` for example, which would fail if the row is not actually valid.
Having a way to skip validations for one operation would be great, for example, using `$row->novalidate->copy`. Same goes for `$rs->novalidate->create` for example.

**Comment by jjn1056** [comment]
done, this is in the latest HEAD with tests and part docs
