### ISSUE TITLE
0.001017 test is failing when Filter-Template is installed

### ISSUE THREAD

**Issue by andk** [jjn1056/Valiant#9]
Sample fail report: http://www.cpantesters.org/cpan/report/5f609396-8d26-11ed-94c1-d4f35de93d87

I have reproduced this result with other perls by testing first without and then again with installed RCAPUTO/Filter-Template-1.043.tar.gz

**Comment by jjn1056** [comment]
@andk thanks for the bug report, I have a fix checked in, it will ship in the next week or so

**Comment by jjn1056** [comment]
@andk pretty sure this is fixed, ping me if not :)
